### ISSUE TITLE
模型量化

### ISSUE THREAD

**Issue by fanqiNO1** [Moemu/Muice-Chatbot#1]
非常好工作！爱来自瓷器！（雾

Hello，在b站刷到了视频，然后有一点想法（

感觉16G显存需求对于大多数人还是有点过高了
不知道您有没有考虑过模型量化之类的事情，量化到4bit的话，显存需求对比于fp16的模型权重会有一半的下降
期待您的新版本！

**Comment by Moemu** [comment]
感谢你的反馈, 我们将在10月初的模型更新中提供int4量化版本. 另外16G显存是推荐配置，不是最低配置，等我去注明一下

**Comment by Crane-32** [comment]
请问后续能否支持采用CPU进行推理？32G内存版本的很多核显轻薄本&小主机跑chatglm2-6B也已经达到堪用水平了。
期待回复！

**Comment by Moemu** [comment]
> 请问后续能否支持采用CPU进行推理？32G内存版本的很多核显轻薄本&小主机跑chatglm2-6B也已经达到堪用水平了。 期待回复！

对于这个请求，以后会实现，在这之前，可以先仿照官方demo修改`llm/chatglm2.py`来实现此功能

**Comment by homo11451419** [comment]
> 非常好工作！爱来自瓷器！（雾
> 
> Hello，在b站刷到了视频，然后有一点想法（
> 
> 感觉16G显存需求对于大多数人还是有点过高了 不知道您有没有考虑过模型量化之类的事情，量化到4bit的话，显存需求对比于fp16的模型权重会有一半的下降 期待您的新版本！
int4能直接运行（我也不知道为啥）
#10 我改完了代码可以参考
直接下载int4模型并放在指定文件夹就行
报错不要管

**Comment by homo11451419** [comment]
不用int4根本跑不起来
<img width="732" alt="image" src="https://github.com/Moemu/Muice-Chatbot/assets/127638251/d236eb7d-5a58-4bed-bf54-deaf255599ec">

**Comment by homo11451419** [comment]
最好不要量化，效果：
问：你知道猫娘嘛

答：唔.......不知道喵！（更加隐藏了自己的猫耳）

问：雪雪喜欢吃什么？

答：唔......很难说明喵！

问：工作又忙又累，还要加班什么的

答：哇.......这可不好说喵！（憔悴不堪）

问：你好

答：你好喵！（依然憔悴不堪）

问：雪雪最近有没有什么值得分享的事情

答：唔.......其实最近没有太多东西可以分享喵！（依旧憔悴不堪）

**Comment by homo11451419** [comment]
随便拉的，感觉不错：
<img width="1280" alt="image" src="https://github.com/Moemu/Muice-Chatbot/assets/127638251/1a969064-f848-4d3f-8703-9e3e89a91ada">

**Comment by Moemu** [comment]
在1.1更新中，已经加入了对CPU推理/int4量化的支持，感谢您的建议
