### ISSUE TITLE
搭建时遇到的问题

### ISSUE THREAD

**Issue by Chaichai438** [Moemu/Muice-Chatbot#11]
代码输入： git clone https://github.com/Moemu/Muice-Chatbot
>> cd Muice-Chatbot
>> conda create --name Muice python=3.10.10
>> conda activate Muice
>> pip install -r requirements.txt

控制台输出：git : 无法将“git”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，
然后再试一次。
所在位置 行:1 字符: 1
+ git clone https://github.com/Moemu/Muice-Chatbot
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
求解Thanks!

**Comment by Moemu** [comment]
烦请按照网络教程安装git，谢谢
