### ISSUE TITLE
模型加载失败, 请检查是否在model目录下放置了初始模型与微调模型，但是已放置且名称正确[Bug]

### ISSUE THREAD

**Issue by whwhwh0715** [Moemu/Muice-Chatbot#15]
### 描述此Bug

清晰简洁的描述。

### 控制台输出

从项目开始运行时控制台的所有输出，注意删减你的个人信息

### 复现该Bug的操作

告诉我们你如何复现此问题

**Comment by xfcgef** [comment]
可能要改一下main.py：读取路径改用绝对路径，或者是try字段下的import部分有问题

（我也踩过这个坑，以上是我个人的解决方案，不保证有用）

**Comment by Moemu** [comment]
给我展示一下你的文件树,确保在程序根目录下运行python

**Comment by Moemu** [comment]
长时间未回复，故关闭issue.
