### ISSUE TITLE
[Bug]ERROR:root:模型加载失败, 请检查是否在model目录下放置了初始模型与微调模型。另外go-cqhttp貌似用不了了

### ISSUE THREAD

**Issue by theskywilldawn** [Moemu/Muice-Chatbot#16]
### 描述此Bug
Muice-Chatbot根目录：
![微信图片_20231012214654](https://github.com/Moemu/Muice-Chatbot/assets/115891468/b13c121e-202f-4faa-b581-d9665fdafc64)
model文件夹下的chatglm2-6b-int4文件夹内部：
![微信图片_20231012214702](https://github.com/Moemu/Muice-Chatbot/assets/115891468/4b4678b0-0ac3-450c-9549-b46f2608ed16)
model文件夹下的Muice文件夹内部：
![微信图片_20231012214707](https://github.com/Moemu/Muice-Chatbot/assets/115891468/b59c511d-e404-4630-9cfa-45f00d6aff9c)
main.py文件:
![微信图片_20231012214822](https://github.com/Moemu/Muice-Chatbot/assets/115891468/83fa4755-89b0-49cf-bae2-cbe1ec38a1b5)

### 控制台输出
![63832458161701](https://github.com/Moemu/Muice-Chatbot/assets/115891468/dde69531-6223-4fb2-80d3-49683961a8df)
若将chatglm2-6b-int4文件夹放在ChatGLM2-6B文件夹内，可正常运行int4模型，因此并非是模型出错。

### 复现该Bug的操作
从GitHub上下载Muice-Chatbot源文件并不小心覆盖已修改的main.py文件。

### 额外信息
之前修改main.py文件后，运行成功了一次，但因go-cqhttp无法连接而失败。后因失误，把原main.py文件覆盖了修改后的main.py文件，且忘记怎么输入的，导致无法再次运行。尝试绝对路径但依然加载模型失败。希望up有空时能帮忙检查下问题所在。
另外因为腾讯围堵，go-cq应该是用不了了，希望能尝试下对接ntqq的方法。
up辛苦了，祝你高考顺利考上理想的大学！

**Comment by Moemu** [comment]
感谢issue，烦请在当前python环境下手动运行以下代码行看看输出情况：
```python
from llm.chatglm2 import Model
model = Model('model/chatglm2-6b-int4','model/Muice')
```

**Comment by Moemu** [comment]
10.20更新：我们已无力提供对qqbot相关代码的更新，详见https://github.com/Moemu/Muice-Chatbot/issues/18 ，目前我们打算提供一个前端页面来完成对沐雪的任何交互，对此带来的不便我深感歉意。

**Comment by Moemu** [comment]
长时间未回复，故关闭issue.
