### ISSUE TITLE
数据是否可以共享一下

### ISSUE THREAD

**Issue by HaimianYu** [Moemu/Muice-Chatbot#17]
你好，能否共享一下训练数据呢

**Comment by Moemu** [comment]
不行呢，训练集的completion差不多是咱自己撰写的呢，共享的话对于我自己损失太大了

**Comment by Moemu** [comment]
训练集部分开源，之后也视成绩起伏继续公开更多的训练集。这可能也是强迫自己学习的一种方式了（笑）
https://huggingface.co/datasets/Moemu/Muice-Dataset
