### ISSUE TITLE
我們是否應該賦予 AI 人格化稱謂？

### ISSUE THREAD

**Issue by TurboHK** [Moemu/Muice-Chatbot#19]
⌈AI 女孩子⌋的設想固然美好，或許還帶有幾分浪漫，但人工智慧系統系統是**程式**和**算法**的集合，**它們**是為了執行特定任務而設計的。**它們**沒有自我意識、**情感**或自主性。在技術層面，將其視為機器或工具更為準確。雖然賦予其人格化的稱謂可以提升用戶體驗（説是⌈顯著提升⌋也不爲過），但身爲開發者必須考慮到一種⌈用戶沈迷其中，而視 AI 爲情感依賴⌋的極端可能。AI畢竟不能取代人類在情感依賴方面的體驗，因此希望您可以在項目的説明文檔中闡明這一點，和/或在模型中加入類似的限制（可參考 ChatGPT 對於此類問題的回答）。

**Comment by Moemu** [comment]
我很欣賞你的理性，但不好意思，你的考慮並不會被大多數用戶所歡迎。 能够運行本項目的受眾不具備“用戶沉迷其中，而視AI為情感依賴”的條件，因為這需要長期的算力支持。 如果用戶視AI為情感依賴，那麼我相信在現實中也不存在能給與其情感依賴的家人或朋友
