### ISSUE TITLE
[enhancement]作者大大可以加一个调用API吗？就是使用第三方代理（不用自己家电脑）

### ISSUE THREAD

**Issue by lueluelue2006** [Moemu/Muice-Chatbot#23]
[enhancement]作者大大可以加一个调用API吗？就是使用第三方代理（不用自己家电脑）

**Comment by Moemu** [comment]
你的意思是说加一个搭建对话服务的API服务器？

**Comment by lueluelue2006** [comment]
搭建服务器可能太麻烦，而且短期之内收益远远小于支出。
我指是像ChatGPT Next Web（https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web）里的BASE_URL和OPENAI_API_KEY那样，调用第三方API
↓↓↓↓↓↓↓↓↓↓↓↓

环境变量：

OPENAI_API_KEY （必填项）
OpanAI 密钥，你在 openai 账户页面申请的 api key，使用英文逗号隔开多个 key，这样可以随机轮询这些 key。

BASE_URL （可选）
Default: https://api.openai.com

Examples: http://your-openai-proxy.com

OpenAI 接口代理 URL，如果你手动配置了 openai 接口代理，请填写此选项。

如果遇到 ssl 证书问题，请将 BASE_URL 的协议设置为 http。

**Comment by QWXL** [comment]
但现在沐雪使用的是自己的模型哎，可能还真不如搭建一个付费的API服务器好办

**Comment by lueluelue2006** [comment]
> 但现在沐雪使用的是自己的模型哎，可能还真不如搭建一个付费的API服务器好办

哦哦哦哦，那确实。
不好意思啦，没仔细看hhh。祝作者大大学业顺利，高考必胜！！！
