### ISSUE TITLE
对onebot协议进行支持

### ISSUE THREAD

**Issue by MoeSnowyFox** [Moemu/Muice-Chatbot#26]
重新编写的main.py并提供onebot服务~不过目前不支持使用指令以及主动对话,未来应该会调试的~

**Comment by MoeSnowyFox** [comment]
[onebot.zip](https://github.com/Moemu/Muice-Chatbot/files/14813152/onebot.zip)

**Comment by MoeSnowyFox** [comment]
将以上两个文件放入\Muice-Chatbot 位置<sub> (main.py的位置啦)</sub>然后配置好onebot服务
(默认http服务监听为8010,http事件上报为http://127.0.0.1:8020) 
目前可用的QQonebot服务建议LLonebot--基于ntqq的LL插件

**Comment by MoeSnowyFox** [comment]
将以上两个文件放入\Muice-Chatbot 位置<sub> (main.py的位置啦)</sub>然后配置好onebot服务
(默认http服务监听为8010,http事件上报为http://127.0.0.1:8020) 
目前可用的QQonebot服务建议LLonebot--基于ntqq的LL插件

**Comment by MoeSnowyFox** [comment]
[https://github.com/LLOneBot/LLOneBot](llonebot仓库)关于onebot支持可能更新缓慢,见谅~
另外感谢大佬的沐雪模型!

**Comment by MoeSnowyFox** [comment]
[https://github.com/LLOneBot/LLOneBot](url)
另外我关于onebot支持可能更新缓慢,见谅~
另外感谢大佬的沐雪模型!

**Comment by Moemu** [comment]
好。慢慢来不用急，感谢您的贡献！

**Comment by MoeSnowyFox** [comment]
onebot服务支持已提交pr~
