### ISSUE TITLE
[Bug]回复文字到页面上发送的时间很慢

### ISSUE THREAD

**Issue by ldqrecord** [Moemu/Muice-Chatbot#44]
### 描述此Bug

清晰简洁的描述。模型返回文字后，到发送时间感觉很慢是为什么

### 控制台输出
<img width="1026" alt="1721830052478" src="https://github.com/user-attachments/assets/96f90785-3344-4c6e-abd2-a28fee04033f">

从项目开始运行时控制台的所有输出，注意删减你的个人信息

### 复现该Bug的操作

告诉我们你如何复现此问题

**Comment by Moemu** [comment]
适应社区要求的模仿真人回复时间，如果不舒服把 https://github.com/Moemu/Muice-Chatbot/blob/1396110d91348fce76cb4f5c988b0fb5df5962fc/ws.py#L112 注释一下/改成
```python
# await asyncio.sleep(len(reply_item) * 0.8)
```

**Comment by ldqrecord** [comment]
感谢
