### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ForeverKing116** [Moemu/Muice-Chatbot#46]
### 描述此Bug

运行main.py 文件后网页显示如下
![屏幕截图 2024-08-06 164730](https://github.com/user-attachments/assets/6dbbf932-4452-40d2-966b-636bbb8f0e08)

### 控制台输出

INFO:     127.0.0.1:53611 - "GET / HTTP/1.1" 404 Not Found

**Comment by Moemu** [comment]
为什么会有一个网页出现？正常情况下不应该打开浏览器

**Comment by Moemu** [comment]
这只是一个后台服务，不用特意打开浏览器。

**Comment by Moemu** [comment]
都没写前端页面，报404正常

**Comment by MoeSnowyFox** [comment]
请使用任意onebotV11适配器链接 而不是使用浏览器

**Comment by ForeverKing116** [comment]
ok，已连接

**Comment by ForeverKing116** [comment]
![屏幕截图 2024-08-09 180649](https://github.com/user-attachments/assets/9917be61-be5d-4256-b600-1a44a08cdf28)
![屏幕截图 2024-08-09 180659](https://github.com/user-attachments/assets/9599d439-192b-4bda-a293-56a6b8fae2cc)
![屏幕截图 2024-08-09 180718](https://github.com/user-attachments/assets/f12c855f-bea0-4397-bc5d-c8e7faa8c03a)
![屏幕截图 2024-08-09 180729](https://github.com/user-attachments/assets/1ca49789-ed6b-46ea-8fbb-a2c7bbded7a7)
![屏幕截图 2024-08-09 180906](https://github.com/user-attachments/assets/3ad8d7f8-171c-44b1-a0f2-3532e723a16e)
configs.json配置完好，且已链接，但似乎发消息没有反应

**Comment by ForeverKing116** [comment]
望解答，谢谢

**Comment by Moemu** [comment]
`model_loader` 用错了，应该为`transformers`
![image](https://github.com/user-attachments/assets/1335084f-05a7-4042-83c4-9e75e0923c50)

**Comment by ForeverKing116** [comment]
我实际上使用的是Qwen模型，经过修改，正确的应如下图
![屏幕截图 2024-08-09 182052](https://github.com/user-attachments/assets/128d7931-f170-43e7-84dc-9dd2d0346e98)

LLOneBot如下
![屏幕截图 2024-08-09 182428](https://github.com/user-attachments/assets/96d96314-b42c-4da2-b324-e4e9081bbe3d)

**Comment by Moemu** [comment]
你下的Muice模型版本号是多少？

**Comment by Moemu** [comment]
你很有可能使用了最新的2.5.3模型，如果真伪如此请重新拉取[Qwen2-1.5B-Instruct-GPTQ-Int4](https://www.modelscope.cn/models/qwen/Qwen2-1.5B-Instruct-GPTQ-Int4/summary)的模型
![image](https://github.com/user-attachments/assets/1acbb07c-5a41-4162-b6b5-5a4a3b1e2ce2)

**Comment by MoeSnowyFox** [comment]
控制台可以看到收到消息的提示吗 若有提示llob就没有问题

**Comment by ForeverKing116** [comment]
谢谢，已经可以了
