### ISSUE TITLE
请问怎么修改可以让chatbot在QQ群聊里跟群友说话

### ISSUE THREAD

**Issue by Tuxaios** [Moemu/Muice-Chatbot#47]

**Comment by Moemu** [comment]
如果只是修改源码的话，只针对被@事件，这可能没有什么难度。
只可惜我不打算更新Chatbot，我将邀请另一位协助者回复此线程。

**Comment by Tuxaios** [comment]
> 如果只是修改源码的话，只针对被@事件，这可能没有什么难度。 只可惜我不打算更新Chatbot，我将邀请另一位协助者回复此线程。

谢谢宝宝

**Comment by Moemu** [comment]
> > 如果只是修改源码的话，只针对被@事件，这可能没有什么难度。 只可惜我不打算更新Chatbot，我将邀请另一位协助者回复此线程。
> 
> 
> 
> 谢谢宝宝，其实我是一个日本人，我很喜欢中国以及中国的it行业的人，他们是如此的伟大，就像您这个项目

不用客气。您居然是日本人吗？这是我第一次见到有外国友人使用我的项目。我也喜欢日本的ACGN文化，以后有机会一定参访

**Comment by MoeSnowyFox** [comment]
目前已经实现, 您可以拉取最新更新使用在群聊中与沐雪聊天!
