### ISSUE TITLE
[Bug]无法处理接受的消息

### ISSUE THREAD

**Issue by CangGuY** [Moemu/Muice-Chatbot#53]
### 描述此Bug
运行后，若收到消息则有如下提示
[INFO] 收到QQ1831045470的消息：Hi
[ERROR] 文件未找到: [Errno 2] No such file or directory: './memory/1831045470.json'
[ERROR] 处理消息时发生错误: GenerationMixin._extract_past_from_model_output() got an unexpected keyword argument 'standardize_cache_format'
同时注意到从模型检查点加载的模型文件中，有些权重没有初始化，而是被新初始化了。这通常意味着模型的预训练权重和加载的模型结构不完全匹配。

### 控制台输出

python main.py
Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at ./model/chatglm2-6b-int4 and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/gu/Muice-Chatbot/llm/transformers.py:22: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  prefix_state_dict = torch.load(os.path.join(pt_model_path, "pytorch_model.bin"), map_location='cpu')
[INFO] Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:     Started server process [10962]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:21050 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 44198) - "WebSocket /ws/api" [accepted]
[INFO] Added job "QQBot.time_work" to job store "default"
[INFO] Scheduler started
INFO:     connection open
[INFO] 已链接
[INFO] 收到QQ1831045470的消息：Hi
[ERROR] 文件未找到: [Errno 2] No such file or directory: './memory/1831045470.json'
[ERROR] 处理消息时发生错误: GenerationMixin._extract_past_from_model_output() got an unexpected keyword argument 'standardize_cache_format'
[INFO] Running job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 17:58:10 CST)" (scheduled at 2024-08-31 17:57:10.522235+08:00)
[INFO] Job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 17:58:10 CST)" executed successfully
[INFO] Running job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 17:59:10 CST)" (scheduled at 2024-08-31 17:58:10.522235+08:00)
[INFO] Job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 17:59:10 CST)" executed successfully
[INFO] Running job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 18:00:10 CST)" (scheduled at 2024-08-31 17:59:10.522235+08:00)
[INFO] Job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 18:00:10 CST)" executed successfully
[INFO] Running job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 18:01:10 CST)" (scheduled at 2024-08-31 18:00:10.522235+08:00)
[INFO] Job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 18:01:10 CST)" executed successfully
[INFO] Running job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 18:02:10 CST)" (scheduled at 2024-08-31 18:01:10.522235+08:00)
[INFO] Job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 18:02:10 CST)" executed successfully
[INFO] Running job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 18:03:10 CST)" (scheduled at 2024-08-31 18:02:10.522235+08:00)
[INFO] Job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 18:03:10 CST)" executed successfully
[INFO] Running job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 18:04:10 CST)" (scheduled at 2024-08-31 18:03:10.522235+08:00)
[INFO] Job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 18:04:10 CST)" executed successfully
[INFO] Running job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 18:05:10 CST)" (scheduled at 2024-08-31 18:04:10.522235+08:00)
[INFO] Job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 18:05:10 CST)" executed successfully
[INFO] Running job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 18:06:10 CST)" (scheduled at 2024-08-31 18:05:10.522235+08:00)
[INFO] Job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 18:06:10 CST)" executed successfully
^CINFO:     Shutting down
[INFO] WebSocket disconnected
INFO:     connection closed
INFO:     Waiting for application shutdown.
[INFO] Scheduler has been shut down
INFO:     Application shutdown complete.
INFO:     Finished server process [10962]

### 复现该Bug的操作

在基于Debian的Linux下部署Muice和llonebot

### 额外信息
int4量化的[ChatGLM2-6B]和2.4版本微调模型
nvidia-smi如下
Sat Aug 31 18:10:28 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.27                 Driver Version: 560.70         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2060        On  |   00000000:01:00.0 Off |                  N/A |
| N/A   74C    P0             33W /   90W |     404MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A        55      G   /Xwayland                                   N/A      |
+-----------------------------------------------------------------------------------------+
另，恭喜开发者高中毕业

**Comment by Moemu** [comment]
感谢您的反馈，关于“有些权重没有初始化，而是被新初始化了。这通常意味着模型的预训练权重和加载的模型结构不完全匹配。”我使用的是ChatGLM2-6B-int4进行微调并作为基底模型进行推理，这似乎无法避免（？

**Comment by Moemu** [comment]
另外您能告诉我您所发送的信息吗？

**Comment by CangGuY** [comment]
> 另外您能告诉我您所发送的信息吗？是私聊还是群聊？

是私聊，仅为测试发送Hi。

**Comment by Moemu** [comment]
好的，您可以告诉我们您的transformers版本号吗？
只需激活环境后运行`pip show transformers`

**Comment by Moemu** [comment]
另外，“文件未找到”问题已经解决，麻烦您这边重新拉取源代码以同步更改

**Comment by CangGuY** [comment]
> transformers

当然，版本号是4.44.2
Name: transformers
Version: 4.44.2
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /root/anaconda3/envs/Muice/lib/python3.10/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by:

**Comment by Moemu** [comment]
根据https://github.com/THUDM/GLM-4/issues/439，您需要降级transformers版本至4.40.2（`pip install transformers==4.40.2`），或者是我们建议的4.32.0

**Comment by CangGuY** [comment]
> 根据 [THUDM/GLM-4#439](https://github.com/THUDM/GLM-4/issues/439) ，您需要降级transformers版本至4.40.2（`pip install transformers==4.40.2`），或者是我们建议的4.32.0

好的，感谢

**Comment by sanerone695** [comment]
FileNotFoundError: [Errno 2] No such file or directory: './model/Muice/pytorch_model.bin'，Where to download pytorch_model.bin?

**Comment by CangGuY** [comment]
You can try "git clone "again or use git pull to get new version
