### ISSUE TITLE
[Bug]Too many values!!!

### ISSUE THREAD

**Issue by Tz-WIND** [Moemu/Muice-Chatbot#55]
### 描述此Bug

没错，还是我，又一个新bug

### 控制台输出

[ERROR] 处理消息时发生错误: too many values to unpack (expected 2)

### 额外信息

今天出现的bug，看起来是在processing_reply函数里报的错
昨天还没有的，就很烦
ps:我自己更改的代码内容与这个部分无关

**Comment by Moemu** [comment]
你的控制台输出就这行？

**Comment by Tz-WIND** [comment]
对，看起来是在处理json时候出的问题
![屏幕截图 2024-09-01 220015](https://github.com/user-attachments/assets/b6c65022-bbfa-411c-abca-669b68d31ff6)

**Comment by Moemu** [comment]
把`main.py`里面的logging.level改成`logging.DEBUG`，然后展示完整输出

**Comment by Moemu** [comment]
重新拉取代码有没有这个问题？

**Comment by Tz-WIND** [comment]
![屏幕截图 2024-09-01 223415](https://github.com/user-attachments/assets/3578e9d8-8a56-41a5-97b2-3ec5a1b9a1f3)

**Comment by Tz-WIND** [comment]
> ![屏幕截图 2024-09-01 223415](https://private-user-images.githubusercontent.com/154044203/363498805-3578e9d8-8a56-41a5-97b2-3ec5a1b9a1f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMDE1ODAsIm5iZiI6MTcyNTIwMTI4MCwicGF0aCI6Ii8xNTQwNDQyMDMvMzYzNDk4ODA1LTM1NzhlOWQ4LThhNTYtNDFhNS05N2IyLTNlYzVhMWI5YTFmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQxNDM0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWRiY2IxOTQxODFhYWExZTAyMzgxZTFkYjA0NThkMGI0ZmQ0YmVhYTNhN2Q0YTAwMGU5MGQ5N2FkZTg5YmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C0LYa-V4zf4DiRMd52WDIFMsmwLo6ilKUkMt8MkZ0hU)

是这行吗

**Comment by Moemu** [comment]
是
![image](https://github.com/user-attachments/assets/a820bb52-1cbd-4962-8d92-62f4c25feeae)

**Comment by Tz-WIND** [comment]
doing

**Comment by Tz-WIND** [comment]
![屏幕截图 2024-09-01 223711](https://github.com/user-attachments/assets/774b632e-61db-4237-9ac7-75fad13cf445)
蚌埠住了，基本没有可用信息

**Comment by Tz-WIND** [comment]
等等，get recent chat memory???

**Comment by Tz-WIND** [comment]
我的叠叠乐叠出问题了？
稍等，我去回退一下代码

**Comment by NaivG** [comment]
看起来是解包json时元组太多导致的，请在报错前添一行`print(str(data))`把data打印出来，以便我们确定问题

**Comment by Tz-WIND** [comment]
问题已解决，我在向model发送历史数据时列表参数过长了

**Comment by Moemu** [comment]
下次提issue的时候先确定是不是自己的改动出了问题，谢谢

**Comment by Tz-WIND** [comment]
抱歉抱歉
