### ISSUE TITLE
一个不成熟的建议

### ISSUE THREAD

**Issue by SinlinLi** [Moemu/Muice-Chatbot#57]
偶然看过一个说法：有人用带有时间戳的数据训练了聊天机器人。当机器人发言时会附带时间戳，这样可以实现类似于人的非实时回复

**Comment by Moemu** [comment]
确实不成熟，因为模型自己都不成熟

**Comment by MoeSnowyFox** [comment]
如果您希望在特定情况（特定时间，随机数）延迟回复，倒是可以考虑添加这个功能

**Comment by Moemu** [comment]
由于您长时间没有回复，我们将关闭此线程
