### ISSUE TITLE
[Bug]微调模型如何启用？

### ISSUE THREAD

**Issue by fantasyxxj** [Moemu/Muice-Chatbot#62]
非常感谢提供这么好的软件。
在release中下载了[Muice-2.7.1-Qwen2.5-7B-Instruct-GPTQ-Int4-8e-4.7z](https://github.com/Moemu/Muice-Chatbot/releases/download/1.4/Muice-2.7.1-Qwen2.5-7B-Instruct-GPTQ-Int4-8e-4.7z)文件之后，直接把解压之后的文件放到./model/muice目录中嘛？感觉对话中并没有用到微调模型：
问题：
你是谁？
回答：
我是一个人工智能，经过训练的计算机程序

在下载的微调模型中，并没有.model文件，这个文件是什么内容？

**Comment by Moemu** [comment]
你把你配置文件发我

**Comment by fantasyxxj** [comment]
配置文件：
# 模型相关
model:
  loader: transformers # 模型加载器 transformers/llmtuner/rwkv-api
  model_path: ./model/chatglm2-6b-int4 # 基底模型路径
  adapter_path: ./model/Muice-chatglm2-6b-int4-pt-128-1e-2 # 微调模型路径

# Bot相关
bot:
  id: 34455 # 机器人QQ号
  port: 21050 # LLOneBot反向WebSocket服务端口
  wait_reply: true # 拟人化回复（回复前等待一段时间）
  cq_code: false # 是否解析CQ码
  anyone: false # 是否回复所有人
  trusted: # 可信QQ号(当anyone为false时生效)
    - 22344 
    - 44556
  group:
    enable: true # 是否启用群聊回复
    only_at: true # 是否只回复at自己的消息
    rate: 0.5 # 群聊回复概率(only_at为false时生效)
    anyone: false # 是否回复所有群组
    trusted: # 可信群组(当anyone为false时生效)
      - 12345678
    only_trusted: false # 是否只回复可信QQ号
    cmd_only_trusted: false # 是否只执行可信QQ号的命令
  nonreply_prefix:  # 不回复消息的前缀
    - '!'
    - '！'
    - '#'

# 主动对话相关
active:
  enable: true # 是否启用主动对话
  rate: 0.003 # 主动对话概率（每分钟）
  active_prompts:
    - '<生成推文: 胡思乱想>'
    - '<生成推文: AI生活>'
    - '<生成推文: AI思考>'
    - '<生成推文: 表达爱意>'
    - '<生成推文: 情感建议>'
  not_disturb: true # 是否开启免打扰模式
  shecdule:
    enable: true # 是否启用定时任务
    rate: 0.75 # 定时任务概率（每次）
    tasks:
      - hour: 8
        prompt: '<日常问候: 早上>'
      - hour: 12
        prompt: '<日常问候: 中午>'
      - hour: 18
        prompt: '<日常问候: 傍晚>'
      - hour: 22
        prompt: '<日常问候: 深夜>'
  targets: # 主动对话目标QQ号
    - 1418587931
    - 554811966

# 其他可选服务
# OFA 图像识别
ofa_image:
  enable: false # 是否启用OFA图像服务
  path: ./model/ofa_image # OFA模型路径

# 语音回复
voice_reply:
  enable: false # 是否启用语音回复
  rate: 0.75 # 语音回复概率

# 实时语音对话(realtime_refence.py)
realtime_voice:
  path: ./model/SenseVoice # 实时语音模型路径

# Faiss长期记忆(Beta)
faiss:
  enable: false # 是否启用Faiss长期记忆
  path: ./model/distiluse-base-multilingual-cased-v1 # Faiss模型路径

以上是配置文件。应该就是改了目录。
![image](https://github.com/user-attachments/assets/da375289-b43e-468b-8309-ff90a91fe7f2)
这是微调模型目录里面的东西。
![image](https://github.com/user-attachments/assets/a0b84c62-62b3-4a3e-99c1-8bc14f17babd)

**Comment by Moemu** [comment]
```
loader: transformers # 模型加载器 transformers/llmtuner/rwkv-api
```

改成

```
loader: llmtuner # 模型加载器 transformers/llmtuner/rwkv-api
```

**Comment by fantasyxxj** [comment]
可我现在用的是ChatGLM模型，
基座是：chatglm2-6b-int4
微调模型是：chatglm2-6b-int4-pt-128-1e-2

看readme，chatglm2写着应该用transformers.

ChatGLM | P-tuning V2 | transformers

然后我换成llmtuner，不管模型执行glm2还是qwen，又是一大堆错误。其中，比较显著的是，llmtuner应该用什么版本？

**Comment by Moemu** [comment]
>FileNotFoundError: Could not find module 'C:\Users\lee.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels_parallel.so' (or one of its dependencies). Try using the full path with constructor syntax.
把两个模型的路径改成绝对路径看看

llmtuner 后期我会改环境，这个先不用管它。

**Comment by fantasyxxj** [comment]
分开两个python环境，可以分别qwen和chatglm2模型跑起来了。但是，都是一样的问题，没有使用微调过的模型。
对于chatglm2模型，修改了：
![image](https://github.com/user-attachments/assets/62746f68-076c-4bea-b8ab-c6e5adf54f94)
没有报so找不到（其实是加载不上的问题。）启动显示：

Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at ./model/chatglm2-6b-int4 and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

![image](https://github.com/user-attachments/assets/31cef346-bc04-41aa-b20f-401173c6d009)

用qweb模型，启动：

[INFO] PyTorch version 2.4.1+cu124 available.
[INFO] HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
[INFO|tokenization_utils_base.py:2209] 2024-12-13 23:13:15,358 >> loading file vocab.json
[INFO|tokenization_utils_base.py:2209] 2024-12-13 23:13:15,359 >> loading file merges.txt
[INFO|tokenization_utils_base.py:2209] 2024-12-13 23:13:15,360 >> loading file tokenizer.json
[INFO|tokenization_utils_base.py:2209] 2024-12-13 23:13:15,361 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:2209] 2024-12-13 23:13:15,363 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:2209] 2024-12-13 23:13:15,364 >> loading file tokenizer_config.json
[INFO|tokenization_utils_base.py:2475] 2024-12-13 23:13:15,852 >> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
12/13/2024 23:13:15 - INFO - llmtuner.data.template - Replace eos token: <|im_end|>
[INFO] Replace eos token: <|im_end|>
[INFO|configuration_utils.py:677] 2024-12-13 23:13:15,870 >> loading configuration file ./model/Qwen2.5-7B-Instruct-GPTQ-Int4\config.json
[INFO|configuration_utils.py:746] 2024-12-13 23:13:15,872 >> Model config Qwen2Config {
  "_name_or_path": "./model/Qwen2.5-7B-Instruct-GPTQ-Int4",
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 3584,
  "initializer_range": 0.02,
  "intermediate_size": 18944,
  "max_position_embeddings": 32768,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 28,
  "num_hidden_layers": 28,
  "num_key_value_heads": 4,
  "quantization_config": {
    "batch_size": 1,
    "bits": 4,
    "block_name_to_quantize": null,
    "cache_block_outputs": true,
    "damp_percent": 0.01,
    "dataset": null,
    "desc_act": false,
    "exllama_config": {
      "version": 1
    },
    "group_size": 128,
    "max_input_length": null,
    "model_seqlen": null,
    "module_name_preceding_first_block": null,
    "modules_in_block_to_quantize": null,
    "pad_token_id": null,
    "quant_method": "gptq",
    "sym": true,
    "tokenizer": null,
    "true_sequential": true,
    "use_cuda_fp16": false,
    "use_exllama": true
  },
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 1000000.0,
  "sliding_window": null,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.46.3",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 152064
}

12/13/2024 23:13:15 - INFO - llmtuner.model.utils.quantization - Loading 4-bit GPTQ-quantized model.
[INFO] Loading 4-bit GPTQ-quantized model.
12/13/2024 23:13:15 - INFO - llmtuner.model.patcher - Using KV cache for faster generation.
[INFO] Using KV cache for faster generation.
[WARNING] CUDA extension not installed.
[WARNING] CUDA extension not installed.
[INFO|modeling_utils.py:3934] 2024-12-13 23:13:16,127 >> loading weights file ./model/Qwen2.5-7B-Instruct-GPTQ-Int4\model.safetensors.index.json
[INFO|modeling_utils.py:1670] 2024-12-13 23:13:16,139 >> Instantiating Qwen2ForCausalLM model under default dtype torch.float16.
[INFO|configuration_utils.py:1096] 2024-12-13 23:13:16,142 >> Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151645
}

C:\Users\lee\miniconda3\envs\muice310\lib\site-packages\transformers\modeling_utils.py:5006: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
[WARNING|logging.py:328] 2024-12-13 23:13:16,181 >> `loss_type=None` was set in the config but it is unrecognised.Using the default loss: `ForCausalLMLoss`.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.60s/it]
[INFO|modeling_utils.py:4800] 2024-12-13 23:13:22,144 >> All model checkpoint weights were used when initializing Qwen2ForCausalLM.

[INFO|modeling_utils.py:4808] 2024-12-13 23:13:22,146 >> All the weights of Qwen2ForCausalLM were initialized from the model checkpoint at ./model/Qwen2.5-7B-Instruct-GPTQ-Int4.
If your task is similar to the task the model of the checkpoint was trained on, you can already use Qwen2ForCausalLM for predictions without further training.
[INFO|configuration_utils.py:1049] 2024-12-13 23:13:22,166 >> loading configuration file ./model/Qwen2.5-7B-Instruct-GPTQ-Int4\generation_config.json
[INFO|configuration_utils.py:1096] 2024-12-13 23:13:22,167 >> Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "pad_token_id": 151643,
  "repetition_penalty": 1.05,
  "temperature": 0.7,
  "top_k": 20,
  "top_p": 0.8
}

12/13/2024 23:13:22 - INFO - llmtuner.model.utils.attention - Using torch SDPA for faster training and inference.
[INFO] Using torch SDPA for faster training and inference.
12/13/2024 23:13:22 - INFO - llmtuner.model.adapter - Upcasting trainable params to float32.
[INFO] Upcasting trainable params to float32.
12/13/2024 23:13:22 - INFO - llmtuner.model.adapter - Fine-tuning method: LoRA
[INFO] Fine-tuning method: LoRA
12/13/2024 23:13:22 - INFO - llmtuner.model.adapter - Loaded adapter(s): ./model/Muice-Qwen2.5-7B-Instruct-GPTQ-Int4
[INFO] Loaded adapter(s): ./model/Muice-Qwen2.5-7B-Instruct-GPTQ-Int4
12/13/2024 23:13:22 - INFO - llmtuner.model.loader - all params: 1110384128
[INFO] all params: 1110384128



其中，有错误：
[WARNING] CUDA extension not installed.

问答：
![image](https://github.com/user-attachments/assets/8863ef58-e9c9-4d8b-af1c-2e1bc2aeceb4)

**Comment by Moemu** [comment]
> Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at ./model/chatglm2-6b-int4 and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

这个100%会出现，没出现就是没有加载到模型。

> [WARNING] CUDA extension not installed.

这个无伤大雅，能用

**Comment by fantasyxxj** [comment]
现在是两个模型都可以运行。就是微调模型没有加载了。一直回答自己是个人工训练的AI。

**Comment by Moemu** [comment]
> 现在是两个模型都可以运行。就是微调模型没有加载了。一直回答自己是个人工训练的AI。

都写了传播爱与和平了，一看就是已经加载了微调模型，你把你历史记忆文件 `./memory` 全删了再看看

**Comment by fantasyxxj** [comment]
对的对的。确实已经加载了。
