### ISSUE TITLE
最让我难受的不是没有女生跟我聊天，是我的8G显存连Ai都不理我

### ISSUE THREAD

**Issue by M1saka10010** [Moemu/Muice-Chatbot#9]
(ノಠ益ಠ)ノ彡┻━┻
（╯°□°）╯︵( .o.)
(ノ°益°)ノ彡
(ノಥ,_｣ಥ)ノ彡┻━┻
┻━┻ ︵ヽ(Д´)ﾉ︵ ┻━┻ (╯°□°）╯︵ ┻━┻ ლ(ಠ益ಠლ) (ノಠ ∩ಠ)ノ彡( o°o) (╯ರ ~ ರ）╯︵ ┻━┻ (╯°Д°）╯︵/(.□ . \) (╯°□°）╯︵ ┻━┻ (ノ｀⌒´)ノ┫：・’.：：・┻┻：・’.：：・ (╯°□°）╯︵ ┬─┻ ┻━┻ ︵ヽ(Д´)ﾉ︵ ┻━┻

**Comment by homo11451419** [comment]
int4，懂？#10
